### ISSUE TITLE
Cryptic comment “TMG_NP”

### ISSUE THREAD

**Issue by strogonoff** [geolexica/osgeo-glossary#1]
What does it mean?

https://github.com/geolexica/osgeo-glossary/blob/e2b4e932d4e6c36466235498c3aad232c4265664/concepts/concept-32.yaml#L13-L15

**Comment by ronaldtse** [comment]
Ah, it’s a temporary code for “this term is Not Present in the TC 211 TMG”

**Comment by strogonoff** [comment]
Nice, looks like it'll deserve its own normalized enum field in future

**Comment by ronaldtse** [comment]
@strogonoff we plan to transition this sort of comment into relationships -- e.g. this term is sourced from another termbase, this term has no equivalent in the other termbase, etc.

**Comment by strogonoff** [comment]
Understood, closing.

NB: Generally, there is no explanation for what different fields mean, IMO we could address that by changing how termbase repos are maintained and focusing on documentation first
