### ISSUE TITLE
Fix duplication of "raster" definition of 337 and 338

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/osgeo-glossary#12]
Raised by @skalee geolexica/osgeo-termbase#8 there is a duplication of the term "raster" as 337 and 338.

id |term |   |   | DEF | EX | NOTE 1 |  NOTE 2 |   |   |   |   |  Source/mod
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
337 | raster |   |   | rectangular grid of pixels like an image | Examples of formats supported by Mapserver are GeoTIFF, JPEG, and PNG | Rasters are supported in MapServer with a layer type of RASTER. |   |   |   |   |   |  
338 | raster |   |   | usually rectangular pattern of parallel scanning lines forming or corresponding to the display on a cathode ray tube |   | A raster is a type of grid. |   | The term “raster data” is often used colloquially in the field of geographic information to identify the whole class of data where the spatial geometry is organized into a grid. |   |   | ISO 19123:2005, 4.1.30, modified — Note 2 to entry has been added.

**Comment by ronaldtse** [comment]
@ReesePlews says there is a new definition from ISO 19123-1 CD that we could use. If so we should replace this with the latest one. Waiting for confirmation.

**Comment by ReesePlews** [comment]
@ronaldtse perhaps at this time, term-id 337 can be removed until 19123-1 has been published

**Comment by ronaldtse** [comment]
Agree. Let’s remove 337! Thanks!

**Comment by skalee** [comment]
Just for clarification: Concepts with the same terms (designations) but different IDs and definitions are supported. That said, it was the only such duplication in the spreadsheet, it caught my eye, and that's why I reported it.

**Comment by ronaldtse** [comment]
@skalee thanks for this. I have removed 337 from the source sheet, and the rest of the entries have been moved up by one (in terms of ID), and re-sorted.

**Comment by ronaldtse** [comment]
(@skalee please help perform a re-import, thanks!)
