### ISSUE TITLE
Update OSGeo glossary to latest Google Sheets (final)

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/osgeo-glossary#7]
https://docs.google.com/spreadsheets/d/1nFOa7qE309C6rbnhJXd0EjUKEiqCDYvgpCJpyTjbhmo/edit?pli=1#gid=222410614

**Comment by ronaldtse** [comment]
This is the final sheet to be imported:
https://docs.google.com/spreadsheets/d/1-F2ES2-F89P7EajWShBKdlPQQI49_vf8zIZeI5oEIn4/edit#gid=671042119

Only the first sheet, "final_for_geolex_loading" is to be imported.

**Comment by ronaldtse** [comment]
@skalee this is urgent -- could you please help handle this first? Thanks!

**Comment by skalee** [comment]
@ronaldtse see https://github.com/geolexica/osgeo-glossary/pull/11, https://github.com/geolexica/osgeo.geolexica.org/pull/37 and https://github.com/geolexica/osgeo-termbase/pull/8. The latter includes some notes and caveats.

**Comment by skalee** [comment]
Updated once again due to yesterday's tweaks in the spreadsheets.
