### ISSUE TITLE
Dealing with comments

### ISSUE THREAD

**Issue by strogonoff** [geolexica/osgeo-glossary#9]
(Blocks #5)

Could we refresh what are comments conceptually? Glossarist doesn’t support comments.

Example of comments: https://github.com/strogonoff/osgeo-glossary/blob/master/concepts/concept-119.yaml#L12

* Can they be migrated as “notes”, or do they not quite fit that?
* If they don’t fit, would OSGeo need them to be preserved?
* If they need to be preserved, what do they seem to apply to best?
    * abstract concept item
    * language-specific item
    * specific revision of a language-specific item
    * some property of language-specific item (definition, particular designation, etc.)

**Comment by strogonoff** [comment]
@ronaldtse Perhaps you remember about OSGeo concept comments?

**Comment by ronaldtse** [comment]
@strogonoff those are purely working comments (i.e. not supposed to be shown).

I'm not sure what is the best solution here. I wonder if we should support non-showing comments within Glossarist only.

**Comment by strogonoff** [comment]
@ronaldtse  Okay, so it’s clear they cannot be migrated as notes.

Do those working comments need to be preserved, or OSGeo has them elsewhere too?

**Comment by ronaldtse** [comment]
We're going to clear off all comments on the official import, so closing this.
